# All we want to do here is get the base image
# and push it to the farmdata2 repo on DockerHub.
#
# We build and store our own images so that we can
# upgrade / update in a fully controlled way.

FROM postgres:12
